mc.version = 26.2

deps.fabric_api = 0.154.2+26.2
deps.fabric-language-kotlin = 1.13.12+kotlin.2.4.0
deps.fabric_permissions = 0.7.0
deps.luckperms = 5.5
deps.polymer = 0.17.4+26.2
deps.server_translations_api = 3.1.0+26.2
deps.sodium = mc26.2-0.9.2-beta.1-fabric
deps.fzzy_config = 0.7.6+26.2

mod.compatible_versions = 26.2